# Generated by Django 3.0.4 on 2020-03-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '주문', 'verbose_name_plural': '주문'},
        ),
        migrations.AlterModelTable(
            name='order',
            table='ys_order',
        ),
    ]
